jellyfin:
  ingress:
    enabled: true
    className: traefik
    hosts:
      - host: jellyfin.k8s.johnchen.dev
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: wildcard-tls-secret
        hosts:
          - jellyfin.k8s.johnchen.dev
  persistence:
    cache:
      enabled: true
    media:
      size: 1000Gi
      accessMode: ReadWriteMany
  nodeSelector:
    runtimeClassName: nvidia
  securityContext:
    runAsUser: 501
