resources:
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-iscsi/refs/heads/master/deploy/csi-iscsi-driverinfo.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-iscsi/refs/heads/master/deploy/csi-iscsi-node.yaml
