app-template:
  controllers:
    main:
      type: deployment
      replicas: 1
      containers:
        main:
          image:
            repository: ghcr.io/paperless-ngx/paperless-ngx
            tag: "2.20"
  service:
    main:
      controller: main
      ports:
        http:
          port: 8000
  persistence:
    data:
      suffix: data
      storageClass: nfs
      accessMode: ReadWriteOnce
      size: 30Gi
      retain: true
      globalMounts:
        - path: /usr/src/paperless/
  ingress:
    main:
      enabled: true
      className: traefik
      hosts:
        - host: paperless.k8s.johnchen.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                name: paperless
                port: 8000
      tls:
        - secretName: wildcard-tls-secret
          hosts:
            - paperless.k8s.johnchen.dev
valkey:
  dataStorage:
    enabled: true
    className: nfs
