app-template:
  controllers:
    main:
      type: deployment
      replicas: 1
      containers:
        main:
          image:
            repository: ghcr.io/paperless-ngx/paperless-ngx
            tag: "2.20"
          env:
            TZ: America/New_York
            PAPERLESS_CONSUMER_POLLING: "10"
            PAPERLESS_DBHOST: paperless-db-rw
            PAPERLESS_REDIS: redis://paperless-valkey:6379
            PAPERLESS_DBENGINE: postgresql
  service:
    main:
      controller: main
      ports:
        http:
          port: 8000
  persistence:
    data:
      storageClass: nfs
      size: 1Gi
      mountPath: /usr/src/paperless/data
    media:
      storageClass: nfs
      size: 8Gi
      mountPath: /usr/src/paperless/media
    export:
      storageClass: nfs
      size: 1Gi
      mountPath: /usr/src/paperless/export
  ingress:
    main:
      enabled: true
      className: traefik
      hosts:
        - host: paperless.k8s.johnchen.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                name: paperless
                port: 8000
      tls:
        - secretName: wildcard-tls-secret
          hosts:
            - paperless.k8s.johnchen.dev
valkey:
  dataStorage:
    enabled: true
    className: nfs
