app-template:
  controllers:
    main:
      type: deployment
      replicas: 1
      containers:
        main:
          image:
            repository: linuxserver/bazarr
            tag: 1.5.4-development
  service:
    main:
      controller: main
      ports:
        http:
          port: 6767
  persistence:
    config:
      enabled: true
      storageClass: nfs
      size: 1Gi
      globalMounts:
        - path: /config
      accessMode: ReadWriteOnce
    tv:
      enabled: true
      storageClass: nfs
      size: 5Gi
      globalMounts:
        - path: /tv
      accessMode: ReadWriteOnce
    movies:
      enabled: true
      storageClass: nfs
      size: 5Gi
      globalMounts:
        - path: /movies
      accessMode: ReadWriteOnce
  ingress:
    main:
      enabled: true
      className: traefik
      hosts:
        - host: bazarr.k8s.johnchen.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                name: bazarr
                port: 6767
      tls:
        - secretName: wildcard-tls-secret
          hosts:
            - bazarr.k8s.johnchen.dev
