pocket-id:
  pocketID:
    image:
      tag: v1.15.0
  ingress:
    enabled: true
    host: pocket-id.k8s.johnchen.dev
    className: traefik
    tls:
      - secretName: wildcard-tls-secret
        hosts:
          - pocket-id.k8s.johnchen.dev
  persistence:
    data:
      enabled: true
