harbor:
  expose:
    tls:
      certSource: secret
      secret:
        secretName: wildcard-tls-secret
  ingress:
    hosts:
      core: harbor.k8s.johnchen.dev
      className: traefik
  externalURL: https://harbor.k8s.johnchen.dev
  persistence:
    persistentVolumeClaim:
      registry:
        storageClass: nfs
      jobservice:
        storageClass: nfs
      redis:
        storageClass: nfs
      trivy:
        storageClass: nfs
